name: Criar ou atualizar README

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Criar um arquivo README.md
        run: |
          echo "# Bem-vindo ao meu repositório" > README.md
          echo "Este é um arquivo README criado automaticamente por um workflow." >> README.md
          echo "Data de criação: $(date)" >> README.md

      - name: Commitar e enviar o README
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Atualizar README.md" || echo "Nenhuma alteração para commitar"
          git push
